/**
 * TypeScript Interfaces mirroring the Backend Pydantic Models
 * (`KubectlCommand`, `TroubleshootingPlan`, `IncidentState`).
 */

export type DangerLevel = 'LOW' | 'MEDIUM' | 'HIGH';

export interface KubectlCommand {
  /** The sequence step number */
  step_number: number;
  /** Title of the step */
  title: string;
  /** The exact kubectl command to execute */
  command: string;
  /** Detailed explanation of what this command does */
  explanation: string;
  /** LOW, MEDIUM, or HIGH */
  danger_level: DangerLevel | string;
  /** Safe read-only alternative (if present) */
  alternative_command?: string | null;
}

export interface TroubleshootingPlan {
  /** Summary of the analyzed problem */
  problem_summary: string;
  /** Classified root-cause Kubernetes cluster error category */
  error_type?: string | null;
  /** List of kubectl command steps in order */
  steps: KubectlCommand[];
  /** URLs/names of K8s documents referenced */
  source_citations: string[];
}

export interface IncidentState {
  /** Unique incident session identifier */
  incident_id: string;
  /** Raw crash logs or error events supplied by SRE */
  raw_logs: string;
  /** Cluster metadata, namespace, or pod context */
  cluster_context?: string | null;
  /** Ordered checklist generated by PlannerAgent */
  planner_checklist?: string[];
  /** Canonical URLs and breadcrumbs retrieved from Vertex AI Search */
  source_citations?: string[];
  /** Complete validated TroubleshootingPlan produced by ExecutorAgent and SafetyGuardian */
  troubleshooting_plan?: TroubleshootingPlan | null;
  /** Current pipeline status: INITIALIZED, PLANNING_COMPLETED, COMPLETED, ERROR */
  status: string;
  /** Session and telemetry metadata */
  metadata?: Record<string, unknown>;
}

export interface DiagnoseApiResponse {
  success: boolean;
  plan?: TroubleshootingPlan | null;
  state?: IncidentState | null;
  error?: string | null;
}
