/**
 * TypeScript Interfaces mirroring the Backend Pydantic Models
 * (`KubectlCommand`, `TroubleshootingPlan`, `IncidentState`).
 */

export type DangerLevel = 'LOW' | 'MEDIUM' | 'HIGH';

export interface KubectlCommand {
  /** The sequence step number */
  step_number: number;
  /** Title of the step */
  title: string;
  /** The exact kubectl command to execute */
  command: string;
  /** Detailed explanation of what this command does */
  explanation: string;
  /** LOW, MEDIUM, or HIGH */
  danger_level: DangerLevel | string;
  /** Safe read-only alternative (if present) */
  alternative_command?: string | null;
}

export interface TroubleshootingPlan {
  /** Summary of the analyzed problem */
  problem_summary: string;
  /** List of kubectl command steps in order */
  steps: KubectlCommand[];
  /** URLs/names of K8s documents referenced */
  source_citations: string[];
}

export interface IncidentState {
  /** Unique incident session identifier */
  incident_id?: string | null;
  /** Raw crash logs or error events supplied by SRE */
  raw_logs: string;
  /** Cluster metadata, namespace, or pod context */
  cluster_context?: string | null;
  /** Ordered checklist generated by PlannerAgent */
  planner_checklist?: string[];
  /** Documentation chunks retrieved via mcp-k8s-docs-server (Vertex AI Search) */
  retrieved_docs?: Record<string, unknown>[];
  /** Canonical URLs and breadcrumbs retrieved from Vertex AI Search */
  source_citations?: string[];
  /** Raw commands proposed by ExecutorAgent */
  raw_command?: KubectlCommand[];
  /** Guarded commands verified by SafetyGuardian */
  final_validated_command?: KubectlCommand[];
  /** Current pipeline status: INITIALIZED, PLANNING, EXECUTING, VALIDATED, COMPLETED, ERROR */
  status: string;
  /** Session and telemetry metadata */
  metadata?: Record<string, unknown>;
  /** Optional embedded TroubleshootingPlan when returned via DiagnoseResponse envelope */
  plan?: TroubleshootingPlan | null;
  /** Convenience top-level accessors for TroubleshootingPlan fields */
  problem_summary?: string;
  steps?: KubectlCommand[];
}

export interface DiagnoseApiResponse {
  success?: boolean;
  plan?: TroubleshootingPlan | null;
  state?: IncidentState | null;
  error?: string | null;
  incident_id?: string;
  problem_summary?: string;
  steps?: KubectlCommand[];
  source_citations?: string[];
}
