"""Data models and Pydantic schemas for the Kubernetes Troubleshooting Copilot."""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, AliasChoices


class KubectlCommand(BaseModel):
    """Structured representation of a single kubectl command step."""
    step_number: int = Field(description="The sequence step number")
    title: str = Field(description="Title of the step")
    command: str = Field(description="The exact kubectl command to execute")
    explanation: str = Field(description="Detailed explanation of what this command does")
    danger_level: str = Field(description="LOW, MEDIUM, or HIGH")
    alternative_command: Optional[str] = Field(None, description="Safe read-only alternative")


class TroubleshootingPlan(BaseModel):
    """Complete structured troubleshooting plan produced by the agentic pipeline."""
    problem_summary: str = Field(description="Summary of the analyzed problem")
    steps: List[KubectlCommand] = Field(description="List of kubectl command steps in order")
    source_citations: List[str] = Field(description="URLs/names of K8s documents referenced")


class IncidentState(BaseModel):
    """State management class tracking the lifecycle of an incident across agents."""
    incident_id: Optional[str] = Field(None, description="Unique incident session identifier")
    raw_logs: str = Field(..., description="Raw crash logs or error events supplied by SRE")
    cluster_context: Optional[str] = Field(None, description="Cluster metadata, namespace, or pod context")
    planner_checklist: Optional[List[str]] = Field(default_factory=list, description="Ordered checklist generated by PlannerAgent")
    retrieved_docs: Optional[List[Dict[str, Any]]] = Field(default_factory=list, description="Documentation chunks retrieved via mcp-k8s-docs-server (Vertex AI Search)")
    source_citations: Optional[List[str]] = Field(default_factory=list, description="Canonical URLs and breadcrumbs retrieved from Vertex AI Search")
    raw_command: Optional[List[KubectlCommand]] = Field(default_factory=list, description="Raw commands proposed by ExecutorAgent")
    final_validated_command: Optional[List[KubectlCommand]] = Field(default_factory=list, description="Guarded commands verified by SafetyGuardian")
    status: str = Field("INITIALIZED", description="Current pipeline status: INITIALIZED, PLANNING, EXECUTING, VALIDATED, COMPLETED, ERROR")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Session and telemetry metadata")


class DiagnoseRequest(BaseModel):
    """API request payload for diagnosing an incident."""
    raw_logs: str = Field(
        ...,
        validation_alias=AliasChoices("raw_logs", "incident_logs"),
        description="Raw Kubernetes crash logs or issue description",
    )
    cluster_context: Optional[str] = Field(None, description="Optional cluster context/namespace")
    incident_id: Optional[str] = Field(None, description="Optional incident ID for session tracking")


class DiagnoseResponse(BaseModel):
    """API response payload containing the generated plan and state."""
    success: bool = Field(..., description="Whether diagnosis succeeded")
    plan: Optional[TroubleshootingPlan] = Field(None, description="Final troubleshooting plan")
    state: Optional[IncidentState] = Field(None, description="Current incident state")
    error: Optional[str] = Field(None, description="Error message if diagnosis failed")


class FeedbackRequest(BaseModel):
    """SRE feedback payload for incident diagnoses."""
    incident_id: str = Field(..., description="Incident ID being reviewed")
    rating: str = Field(..., description="'thumbs_up' or 'thumbs_down'")
    comments: Optional[str] = Field(None, description="Optional SRE feedback or correction comments")
    user_id: Optional[str] = Field("sre-user", description="User ID submitting feedback")


class FeedbackResponse(BaseModel):
    """Response acknowledging feedback receipt."""
    success: bool = Field(True, description="Whether feedback was recorded")
    message: str = Field("Feedback recorded successfully", description="Status message")
